https://launchschool.com/exercises/3a8777d5

***What will the following code print, and why?***

```ruby
a = 7
array = [1, 2, 3]

def my_value(ary)
  ary.each do |b|
    a += b
  end
end

my_value(array)
puts a
```

***Answers:***

This program will raise an exception when reaches line 11
after calling `my_value`: it is a reassigning operation 
performed on a variable `a` that has not been initialized 
yet in the method's definition scope, as it is self-contained,
in respect to the outer scope as we have seen. 
The outer scope `a` is not reachable from  within the method's 
definition, even if it inside the `each`code block: `each` 
invocation still happens inside the method definition of `my_value`.