# Exercise 08

Valentina is using a new task manager program she wrote. When interacting with her task manager, an error is raised that surprises her. Can you find the bug and fix it?

```ruby
class TaskManager
  attr_reader :owner
  attr_accessor :tasks

  def initialize(owner)
    @owner = owner
    @tasks = []
  end

  def add_task(name, priority=:normal)
    task = Task.new(name, priority)
    tasks.push(task)
  end

  def complete_task(task_name)
    completed_task = nil

    tasks.each do |task|
      completed_task = task if task.name == task_name
    end

    if completed_task
      tasks.delete(completed_task)
      puts "Task '#{completed_task.name}' complete! Removed from list."
    else
      puts "Task not found."
    end
  end

  def display_all_tasks
    display(tasks)
  end

  def display_high_priority_tasks
    # Before:
    # tasks = tasks.select do |task|
    #           task.priority == :high
    #         end

    # Added:
    high_priority_tasks = tasks.select do |task|
                            task.priority == :high
                          end

    display(high_priority_tasks)
  end

  private

  def display(tasks)
    puts "--------"
    tasks.each do |task|
      puts task
    end
    puts "--------"
  end
end

class Task
  attr_accessor :name, :priority

  def initialize(name, priority=:normal)
    @name = name
    @priority = priority
  end

  def to_s
    "[" + sprintf("%-6s", priority) + "] #{name}"
  end
end

valentinas_tasks = TaskManager.new('Valentina')

valentinas_tasks.add_task('pay bills', :high)
valentinas_tasks.add_task('read OOP book')
valentinas_tasks.add_task('practice Ruby')
valentinas_tasks.add_task('run 5k', :low)

valentinas_tasks.complete_task('read OOP book')

valentinas_tasks.display_all_tasks
valentinas_tasks.display_high_priority_tasks
```

In this case the problem was that we were shadowing the getter `tasks` from the `TaskManager` class with a local variable of the same name `tasks`, inside the scope of the `display_high_priority_tasks` instance method. What happened was that Ruby pre-loads any local variables that could be used in the definition with a value of `nil`. So, by the time the method definition code begins to run, we have lost the access to the getter `tasks`, because it has been _shadowed_ by the local variable with the same name. The solution is easy: we just have to change the name of the variable, something clear and unique like `high_priority_tasks`, to get te desired results. This demonstrates that it's not a good idea to name variables with the same name as other methods or other variables.